[phases.setup]
nixPkgs = ["python3", "git", "flutter", "nginx"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip --no-warn-script-location",
  "cd backend && pip3 install -r requirements.txt --no-warn-script-location",
  "cd frontend && flutter pub get && flutter clean && flutter config --enable-web"
]

[phases.build]
cmds = [
  "cd frontend && flutter build web --release",
  "mkdir -p public",
  "cp -r frontend/build/web/* public/"
]

[start]
cmd = "bash scripts/start.sh" 