[phases.setup]
nixPkgs = ["python3", "git", "flutter"]

[phases.install]
cmds = [
  "cd backend && pip install -r requirements.txt",
  "cd frontend && flutter pub get"
]

[phases.build]
cmds = [
  "cd frontend && flutter build web --release",
  "mkdir -p backend/static",
  "cp -r frontend/build/web/* backend/static/"
]

[start]
cmd = "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT" 