[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "git", "flutter", "nginx"]

[phases.install]
cmds = [
  "cd backend && python3 -m pip install -r requirements.txt",
  "cd frontend && flutter pub get && flutter clean && flutter config --enable-web"
]

[phases.build]
cmds = [
  "cd frontend && flutter build web --release",
  "mkdir -p public",
  "cp -r frontend/build/web/* public/"
]

[start]
cmd = "bash scripts/start.sh" 