name: Frontend Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-tests.yml'
      - 'justfile'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-tests.yml'
      - 'justfile'

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Install Just
      uses: taiki-e/install-action@just
      
    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: |
          frontend/.dart_tool
          frontend/build
          ${{ env.PUB_CACHE }}
        key: ${{ runner.os }}-flutter-${{ hashFiles('frontend/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-
          
    - name: Install frontend dependencies
      run: just install-frontend
      
    - name: Run frontend tests
      run: just test-frontend
      
    - name: Run frontend tests with coverage
      run: just test-frontend-coverage
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: frontend/coverage/lcov.info
        flags: frontend
        name: frontend-coverage
        fail_ci_if_error: false 