name: Status

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  status-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Install Just
      uses: taiki-e/install-action@just
      
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          backend/venv
          frontend/.dart_tool
          ~/.cache/pip
        key: ${{ runner.os }}-status-${{ hashFiles('backend/requirements.txt', 'frontend/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-status-
          
    - name: Install dependencies
      shell: bash
      run: |
        just install-backend
        just install-frontend
        
    - name: Run quick health check
      shell: bash
      run: |
        echo "## Project Status" >> $GITHUB_STEP_SUMMARY
        echo "✅ Backend dependencies installed" >> $GITHUB_STEP_SUMMARY
        echo "✅ Frontend dependencies installed" >> $GITHUB_STEP_SUMMARY
        echo "✅ Just task runner available" >> $GITHUB_STEP_SUMMARY
        
        # Check if basic commands work
        just status >> $GITHUB_STEP_SUMMARY || echo "⚠️ Status check failed" >> $GITHUB_STEP_SUMMARY
        
    - name: Verify project structure
      shell: bash
      run: |
        echo "## Project Structure Check" >> $GITHUB_STEP_SUMMARY
        
        # Check if key directories exist
        if [ -d "backend" ]; then echo "✅ Backend directory exists" >> $GITHUB_STEP_SUMMARY; else echo "❌ Backend directory missing" >> $GITHUB_STEP_SUMMARY; fi
        if [ -d "frontend" ]; then echo "✅ Frontend directory exists" >> $GITHUB_STEP_SUMMARY; else echo "❌ Frontend directory missing" >> $GITHUB_STEP_SUMMARY; fi
        if [ -f "justfile" ]; then echo "✅ Justfile exists" >> $GITHUB_STEP_SUMMARY; else echo "❌ Justfile missing" >> $GITHUB_STEP_SUMMARY; fi
        if [ -f "README.md" ]; then echo "✅ README exists" >> $GITHUB_STEP_SUMMARY; else echo "❌ README missing" >> $GITHUB_STEP_SUMMARY; fi 